version: '3.8'

services:
  golang:
    image: test
    ports:
      - "8080:8080"
    deploy:
      replicas: 1

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
